# render.yaml

services:
  - type: web
    name: vite-react-shadcn-app
    env: node
    plan: free
    region: ohio
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
    autoDeploy: true